all:
	#g++ -fPIC -g -c -Wall clusteringutils.cpp
	#g++ -shared -o libclusteringutils.so clusteringutils.o
	#cp libclusteringutils.so ../../lib
	#cp clusteringutils.h ../../common/inc
	
clean:
	#rm clusteringutils.o libclusteringutils.so
	#rm ../../lib/libclusteringutils.so
	#rm ../../common/inc/clusteringutils.h